package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/akemoon/crowdfunding-app-project/domain"
	"github.com/akemoon/crowdfunding-app-project/graph/model"
	"github.com/google/uuid"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (bool, error) {
	err := r.svc.CreateProject(ctx, input.UserID, domain.CreateProjectReq{
		Category:     domain.Category(input.Category),
		Name:         input.Name,
		Description:  input.Description,
		Currency:     domain.Currency(input.Currency),
		GoalAmount:   int64(input.GoalAmount),
		DurationDays: int(input.DurationDays),
	})
	return err == nil, err
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id uuid.UUID, input model.UpdateProjectInput) (bool, error) {
	err := r.svc.UpdateProject(ctx, input.UserID, id, domain.CreateProjectReq{
		Category:     domain.Category(input.Category),
		Name:         input.Name,
		Description:  input.Description,
		Currency:     domain.Currency(input.Currency),
		GoalAmount:   int64(input.GoalAmount),
		DurationDays: int(input.DurationDays),
	})
	return err == nil, err
}

// TakeApplication is the resolver for the takeApplication field.
func (r *mutationResolver) TakeApplication(ctx context.Context, id uuid.UUID, moderatorID uuid.UUID) (bool, error) {
	err := r.svc.TakeApplicationForce(ctx, id, moderatorID)
	return err == nil, err
}

// ApproveProject is the resolver for the approveProject field.
func (r *mutationResolver) ApproveProject(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.svc.ApproveProject(ctx, id)
	return err == nil, err
}

// RejectProject is the resolver for the rejectProject field.
func (r *mutationResolver) RejectProject(ctx context.Context, id uuid.UUID, reason string) (bool, error) {
	err := r.svc.RejectProject(ctx, id, reason)
	return err == nil, err
}

// BoostProject is the resolver for the boostProject field.
func (r *mutationResolver) BoostProject(ctx context.Context, id uuid.UUID, userID uuid.UUID, promoCode string) (bool, error) {
	err := r.svc.BoostProject(ctx, userID, id, promoCode)
	return err == nil, err
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id uuid.UUID) (*model.Project, error) {
	p, err := r.svc.GetProjectByIDRaw(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapProject(p), nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, filter *model.ProjectsFilter) ([]*model.Project, error) {
	req := domain.GetProjectsReq{
		Status: domain.StatusActive,
		Sort:   domain.SortDefault,
		Limit:  20,
	}

	if filter != nil {
		if filter.Status != nil {
			req.Status = domain.Status(*filter.Status)
		}
		if filter.Sort != nil {
			req.Sort = domain.Sort(*filter.Sort)
		}
		if filter.Category != nil {
			c := domain.Category(*filter.Category)
			req.Category = &c
		}
		if filter.Search != nil {
			req.Search = filter.Search
		}
		if filter.Limit != nil {
			req.Limit = int(*filter.Limit)
		}
		if filter.Offset != nil {
			req.Offset = int(*filter.Offset)
		}
	}

	resp, err := r.svc.GetProjects(ctx, req)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Project, len(resp.Items))
	for i, p := range resp.Items {
		out[i] = mapProject(p)
	}
	return out, nil
}

// ProjectsByUser is the resolver for the projectsByUser field.
func (r *queryResolver) ProjectsByUser(ctx context.Context, userID uuid.UUID) ([]*model.Project, error) {
	projects, err := r.svc.GetProjectsByUserID(ctx, userID, true)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Project, len(projects))
	for i, p := range projects {
		out[i] = mapProject(p)
	}
	return out, nil
}

// PendingApplications is the resolver for the pendingApplications field.
func (r *queryResolver) PendingApplications(ctx context.Context) ([]*model.Application, error) {
	apps, err := r.svc.GetPendingApplications(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Application, len(apps))
	for i, a := range apps {
		out[i] = mapApplication(a)
	}
	return out, nil
}

// MyApplications is the resolver for the myApplications field.
func (r *queryResolver) MyApplications(ctx context.Context, moderatorID uuid.UUID) ([]*model.Application, error) {
	apps, err := r.svc.GetMyApplications(ctx, moderatorID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Application, len(apps))
	for i, a := range apps {
		out[i] = mapApplication(a)
	}
	return out, nil
}

// ApplicationByProject is the resolver for the applicationByProject field.
func (r *queryResolver) ApplicationByProject(ctx context.Context, projectID uuid.UUID) (*model.Application, error) {
	p, err := r.svc.GetProjectByIDRaw(ctx, projectID)
	if err != nil {
		return nil, err
	}
	a, err := r.svc.GetApplicationByProjectID(ctx, projectID, p.UserID)
	if err != nil {
		return nil, err
	}
	return mapApplication(a), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
