// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Application struct {
	Status       string     `json:"status"`
	RejectReason *string    `json:"rejectReason,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	AssignedAt   *time.Time `json:"assignedAt,omitempty"`
	ProcessedAt  *time.Time `json:"processedAt,omitempty"`
	Project      *Project   `json:"project,omitempty"`
}

type CreateProjectInput struct {
	UserID       uuid.UUID `json:"userID"`
	Category     string    `json:"category"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Currency     string    `json:"currency"`
	GoalAmount   int32     `json:"goalAmount"`
	DurationDays int32     `json:"durationDays"`
}

type Mutation struct {
}

type Project struct {
	ID            uuid.UUID  `json:"id"`
	UserID        uuid.UUID  `json:"userID"`
	Category      string     `json:"category"`
	Name          string     `json:"name"`
	Description   string     `json:"description"`
	Currency      string     `json:"currency"`
	GoalAmount    int32      `json:"goalAmount"`
	CurrentAmount int32      `json:"currentAmount"`
	DurationDays  int32      `json:"durationDays"`
	Status        string     `json:"status"`
	IsBoosted     bool       `json:"isBoosted"`
	StartedAt     *time.Time `json:"startedAt,omitempty"`
	BoostedUntil  *time.Time `json:"boostedUntil,omitempty"`
}

type ProjectsFilter struct {
	Status   *string `json:"status,omitempty"`
	Category *string `json:"category,omitempty"`
	Search   *string `json:"search,omitempty"`
	Sort     *string `json:"sort,omitempty"`
	Limit    *int32  `json:"limit,omitempty"`
	Offset   *int32  `json:"offset,omitempty"`
}

type Query struct {
}

type UpdateProjectInput struct {
	UserID       uuid.UUID `json:"userID"`
	Category     string    `json:"category"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Currency     string    `json:"currency"`
	GoalAmount   int32     `json:"goalAmount"`
	DurationDays int32     `json:"durationDays"`
}
