// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/manager/applications/{id}/approve": {
            "post": {
                "description": "Approves a project application and moves project to active.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager"
                ],
                "summary": "Approve project application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User role (must be Manager)",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status=ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid project id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "project_not_on_review",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    },
                    "500": {
                        "description": "internal_error",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    }
                }
            }
        },
        "/manager/applications/{id}/reject": {
            "post": {
                "description": "Rejects a project application with reason.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager"
                ],
                "summary": "Reject project application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User role (must be Manager)",
                        "name": "X-User-Role",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reject reason payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RejectProjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status=ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid project id | invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "project_not_on_review",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    },
                    "500": {
                        "description": "internal_error",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "description": "Returns a paginated list of projects filtered by status, category and search.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project"
                ],
                "summary": "Get projects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Status filter (active|finished), default: active",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (default|date), default: default",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category filter (science|tech|architecture_and_urban|sport|music)",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (1-100, default: 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetProjectsResp"
                        }
                    },
                    "400": {
                        "description": "unknown_status | unknown_sort | unknown_category",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    },
                    "500": {
                        "description": "internal_error",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new project by given payload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project"
                ],
                "summary": "Create project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Project create payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateProjectReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "validation_error | invalid request body",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "project_exists",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    },
                    "500": {
                        "description": "internal_error",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    }
                }
            }
        },
        "/projects/{id}": {
            "get": {
                "description": "Returns a project by its id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project"
                ],
                "summary": "Get project by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Project"
                        }
                    },
                    "400": {
                        "description": "invalid project id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "project_not_found",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    },
                    "405": {
                        "description": "method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal_error",
                        "schema": {
                            "$ref": "#/definitions/httplib.ErrResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Category": {
            "type": "string",
            "enum": [
                "science",
                "tech",
                "architecture_and_urban",
                "sport",
                "music"
            ],
            "x-enum-varnames": [
                "CategoryScience",
                "CategoryTech",
                "CategoryArchitectureAndUrban",
                "CategorySport",
                "CategoryMusic"
            ]
        },
        "domain.CreateProjectReq": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "currency": {
                    "$ref": "#/definitions/domain.Currency"
                },
                "description": {
                    "type": "string"
                },
                "durationDays": {
                    "type": "integer"
                },
                "goalAmount": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Currency": {
            "type": "string",
            "enum": [
                "RUB",
                "USD"
            ],
            "x-enum-varnames": [
                "CurrencyRUB",
                "CurrencyUSD"
            ]
        },
        "domain.GetProjectsResp": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Project"
                    }
                }
            }
        },
        "domain.Project": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "currency": {
                    "$ref": "#/definitions/domain.Currency"
                },
                "currentAmount": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "durationDays": {
                    "type": "integer"
                },
                "goalAmount": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isBoosted": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.Status"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "domain.Status": {
            "type": "string",
            "enum": [
                "review",
                "active",
                "finished"
            ],
            "x-enum-varnames": [
                "StatusReview",
                "StatusActive",
                "StatusFinished"
            ]
        },
        "handler.RejectProjectReq": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "httplib.ErrResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Project service API",
	Description:      "Projects service API for a crowdfunding app.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
